/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sales.sytem.frontend.view;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/**
 *
 * @author ro
 */


public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCloseSession = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmenu = new javax.swing.JMenu();
        mnuSeeProduct = new javax.swing.JMenuItem();
        mnuSeeCategory = new javax.swing.JMenuItem();
        jmenut = new javax.swing.JMenu();
        mnuAddProductToInven = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuOuputProductToInven = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuStore = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuSupplier = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        mnuCloseSession.setText("usuario");

        jMenuItem1.setText("cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuCloseSession.add(jMenuItem1);

        jMenuBar1.add(mnuCloseSession);

        jmenu.setText("product");

        mnuSeeProduct.setText("ver productos");
        mnuSeeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeeProductActionPerformed(evt);
            }
        });
        jmenu.add(mnuSeeProduct);

        mnuSeeCategory.setText("categorias");
        mnuSeeCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeeCategoryActionPerformed(evt);
            }
        });
        jmenu.add(mnuSeeCategory);

        jMenuBar1.add(jmenu);

        jmenut.setText("entrada de productos");

        mnuAddProductToInven.setText("añadir productos al almacen");
        mnuAddProductToInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddProductToInvenActionPerformed(evt);
            }
        });
        jmenut.add(mnuAddProductToInven);

        jMenuBar1.add(jmenut);

        jMenu3.setText("salida de productos");

        mnuOuputProductToInven.setText("registrar salida de almacen");
        mnuOuputProductToInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOuputProductToInvenActionPerformed(evt);
            }
        });
        jMenu3.add(mnuOuputProductToInven);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("ventas");

        jMenuItem2.setText("Realizar Venta");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ver Ventas");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("tiendas");

        mnuStore.setText("ver tiendas");
        mnuStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStoreActionPerformed(evt);
            }
        });
        jMenu5.add(mnuStore);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("proveedores");

        mnuSupplier.setText("ver proveedores");
        mnuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSupplierActionPerformed(evt);
            }
        });
        jMenu6.add(mnuSupplier);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuOuputProductToInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOuputProductToInvenActionPerformed
      ProductOutStoreView enr=new ProductOutStoreView();
      if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        } // TODO add your handling code here:
    }//GEN-LAST:event_mnuOuputProductToInvenActionPerformed

    private void mnuSeeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeeProductActionPerformed
      ProductView enr=new ProductView();
      if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        } 
    }//GEN-LAST:event_mnuSeeProductActionPerformed

    private void mnuSeeCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeeCategoryActionPerformed
      ProductCategoryView enr=new ProductCategoryView();
      if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuSeeCategoryActionPerformed

    private void mnuAddProductToInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddProductToInvenActionPerformed
      ProductEntryWarehouseView enr=new ProductEntryWarehouseView();
      if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuAddProductToInvenActionPerformed

    private void mnuStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStoreActionPerformed
      StoreView enr=new StoreView();
      if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuStoreActionPerformed

    private void mnuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSupplierActionPerformed
      SupplierView enr=new SupplierView();
      if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuSupplierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmenu;
    private javax.swing.JMenu jmenut;
    private javax.swing.JMenuItem mnuAddProductToInven;
    private javax.swing.JMenu mnuCloseSession;
    private javax.swing.JMenuItem mnuOuputProductToInven;
    private javax.swing.JMenuItem mnuSeeCategory;
    private javax.swing.JMenuItem mnuSeeProduct;
    private javax.swing.JMenuItem mnuStore;
    private javax.swing.JMenuItem mnuSupplier;
    // End of variables declaration//GEN-END:variables
}
