/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sales.sytem.frontend.view;

import javax.swing.JOptionPane;

/**
 *
 * @author ro
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MDI() {
        initComponents();
        setTitle("Inversiones y Representaciones JOE Glass");
        this.setExtendedState(MDI.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCloseSession = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuPr = new javax.swing.JMenu();
        mnuSeeProduct = new javax.swing.JMenuItem();
        mnuSeeCategory = new javax.swing.JMenuItem();
        mnuEntAlm = new javax.swing.JMenu();
        mnuAddProductToInven = new javax.swing.JMenuItem();
        mnuWerehouseStock = new javax.swing.JMenuItem();
        mnuSalTien = new javax.swing.JMenu();
        mnuOuputProductToInven = new javax.swing.JMenuItem();
        mnuStoreStock = new javax.swing.JMenuItem();
        mnuVent = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuTien = new javax.swing.JMenu();
        mnuStore = new javax.swing.JMenuItem();
        mnuProvee = new javax.swing.JMenu();
        mnuSupplier = new javax.swing.JMenuItem();
        mnuClient = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N

        mnuCloseSession.setText("Usuario");
        mnuCloseSession.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jMenuItem6.setText("Administrador de usuarios");
        mnuCloseSession.add(jMenuItem6);

        jMenuItem1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jMenuItem1.setText("cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuCloseSession.add(jMenuItem1);

        jMenuBar1.add(mnuCloseSession);

        mnuPr.setText("Product");
        mnuPr.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        mnuSeeProduct.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuSeeProduct.setText("ver productos");
        mnuSeeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeeProductActionPerformed(evt);
            }
        });
        mnuPr.add(mnuSeeProduct);

        mnuSeeCategory.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuSeeCategory.setText("categorias");
        mnuSeeCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeeCategoryActionPerformed(evt);
            }
        });
        mnuPr.add(mnuSeeCategory);

        jMenuBar1.add(mnuPr);

        mnuEntAlm.setText("Entrada de productos");
        mnuEntAlm.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        mnuAddProductToInven.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuAddProductToInven.setText("añadir productos al almacén");
        mnuAddProductToInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddProductToInvenActionPerformed(evt);
            }
        });
        mnuEntAlm.add(mnuAddProductToInven);

        mnuWerehouseStock.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuWerehouseStock.setText("stock");
        mnuWerehouseStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWerehouseStockActionPerformed(evt);
            }
        });
        mnuEntAlm.add(mnuWerehouseStock);

        jMenuBar1.add(mnuEntAlm);

        mnuSalTien.setText("Salida de productos");
        mnuSalTien.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        mnuOuputProductToInven.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuOuputProductToInven.setText("registrar salida de almacén");
        mnuOuputProductToInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOuputProductToInvenActionPerformed(evt);
            }
        });
        mnuSalTien.add(mnuOuputProductToInven);

        mnuStoreStock.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuStoreStock.setText("stock");
        mnuStoreStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStoreStockActionPerformed(evt);
            }
        });
        mnuSalTien.add(mnuStoreStock);

        jMenuBar1.add(mnuSalTien);

        mnuVent.setText("Ventas");
        mnuVent.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jMenuItem2.setText("realizar venta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuVent.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jMenuItem4.setText("Stock");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuVent.add(jMenuItem4);

        jMenuBar1.add(mnuVent);

        mnuTien.setText("Tiendas");
        mnuTien.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        mnuStore.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuStore.setText("ver tiendas");
        mnuStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStoreActionPerformed(evt);
            }
        });
        mnuTien.add(mnuStore);

        jMenuBar1.add(mnuTien);

        mnuProvee.setText("Proveedores");
        mnuProvee.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        mnuSupplier.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        mnuSupplier.setText("ver proveedores");
        mnuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSupplierActionPerformed(evt);
            }
        });
        mnuProvee.add(mnuSupplier);

        jMenuBar1.add(mnuProvee);

        mnuClient.setText("Clientes");
        mnuClient.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jMenuItem3.setText("ver clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuClient.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jMenuItem5.setText("jMenuItem5");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuClient.add(jMenuItem5);

        jMenuBar1.add(mnuClient);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cerrar();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuOuputProductToInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOuputProductToInvenActionPerformed
        ProductOutStoreView enr = new ProductOutStoreView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        } // TODO add your handling code here:
    }//GEN-LAST:event_mnuOuputProductToInvenActionPerformed

    private void mnuSeeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeeProductActionPerformed
        ProductView enr = new ProductView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuSeeProductActionPerformed

    private void mnuSeeCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeeCategoryActionPerformed
        ProductCategoryView enr = new ProductCategoryView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuSeeCategoryActionPerformed

    private void mnuAddProductToInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddProductToInvenActionPerformed
        ProductEntryWarehouseView enr = new ProductEntryWarehouseView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuAddProductToInvenActionPerformed

    private void mnuStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStoreActionPerformed
        StoreView enr = new StoreView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuStoreActionPerformed

    private void mnuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSupplierActionPerformed
        SupplierView enr = new SupplierView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuSupplierActionPerformed

    private void mnuWerehouseStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWerehouseStockActionPerformed
        WarehouseStockView enr = new WarehouseStockView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuWerehouseStockActionPerformed

    private void mnuStoreStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStoreStockActionPerformed
        StoreStockView enr = new StoreStockView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_mnuStoreStockActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SaleView enr = new SaleView();
        if (enr.isShowing()) {
            //enr.getFocusListeners();
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CustomerView enr = new CustomerView();
        if (enr.isShowing()) {
            //enr.getFocusListeners();
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       StoreStockView enr = new StoreStockView();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         Tesdff enr = new Tesdff();
        if (enr.isShowing()) {
        } else {
            enr.setVisible(true);
            jDesktopPane.add(enr);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea cerrar la aplicacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mnuAddProductToInven;
    public javax.swing.JMenu mnuClient;
    private javax.swing.JMenu mnuCloseSession;
    public javax.swing.JMenu mnuEntAlm;
    private javax.swing.JMenuItem mnuOuputProductToInven;
    public javax.swing.JMenu mnuPr;
    public javax.swing.JMenu mnuProvee;
    public javax.swing.JMenu mnuSalTien;
    private javax.swing.JMenuItem mnuSeeCategory;
    private javax.swing.JMenuItem mnuSeeProduct;
    private javax.swing.JMenuItem mnuStore;
    private javax.swing.JMenuItem mnuStoreStock;
    private javax.swing.JMenuItem mnuSupplier;
    public javax.swing.JMenu mnuTien;
    private javax.swing.JMenu mnuVent;
    private javax.swing.JMenuItem mnuWerehouseStock;
    // End of variables declaration//GEN-END:variables
}
